### ISSUE TITLE
Does this work from an ATMEGA328 to a SAMD21?

### ISSUE THREAD

**Issue by mjbmikeb2** [PowerBroker2/SerialTransfer#62]
A struct containing individual bytes transfers OK but a struct containing ints and floats get messed up.
The documentation doesn't mention inter-platform compatibility.

**Comment by PowerBroker2** [comment]
The library works across platforms as long as the endianness and type sizes match. The MCUs you mentioned are both little endian, so that isn't a problem. However, the ATMEGA is an 8-bit MCU and the SAMD is 32-bit, meaning, if you say `int` without specifying a byte-size (i.e. `int16_t`), you will have parsing issues. My guess is you are using `int`, but using `int16_t` will solve your issue.

**Comment by mjbmikeb2** [comment]
Turned out to be a padding issue. Adding
__attribute__((packed))
to the struct definition on the 32 bit end made it compatible with the serialised format of the 8 bit struct which doesn't do padding.
Depending on the layout of the struct, the padding on 32 bit platform can significantly increases the serialised size.
You might want to mention this in the documentation or examples.
